baseurl = "http://pylhr.github.io"
title = "pylhr"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Priyanshu Lohar"
  info = "Digital Portfolio"
  description = "Priyanshu's online repository"
  keywords = "blog,developer,personal"
  avatarurl = "/images/avatar_mine.jpeg"
  #gravatar = "priyanshulohar1@gmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2024

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[params.goatCounter]
  code = "pylhr"
  
# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/pylhr/"

[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/pylhr/"

[[params.social]]
  name = "Youtube"
  icon = "fa fa-youtube fa-2x"
  weight = 2
  url = "https://www.youtube.com/@pylhr"

[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 3  
  url = "https://www.linkedin.com/in/priyanshu-lohar-13559515b/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"
